package:
  name: abstract-rendering
  version: master

source:
  git_url: git://github.com/JosephCottam/AbstractRendering.git
#  git_tag:

requirements:
  build:
    - python
  run:
    - python
    - numpy

test:
  imports:
    - abstract_rendering
    - abstract_rendering.fast_project

about:
  home: https://github.com/JosephCottam/AbstractRendering
  license: 3rd-clause BSD (https://github.com/JosephCottam/AbstractRendering/blob/master/LICENSE)
