package:
  name: restructuredtext-lint
  version: !!str 0.6.0

source:
  fn: restructuredtext_lint-0.6.0.tar.gz
  url: https://pypi.python.org/packages/source/r/restructuredtext_lint/restructuredtext_lint-0.6.0.tar.gz
  md5: d233e36e37212af6626fe5a8106c56d3
#  patches:
   # List any patch files here
   # - fix.patch

build:
  #preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - restructuredtext_lint = restructuredtext_lint:main
    #
    # Would create an entry point called restructuredtext_lint that calls restructuredtext_lint.main()

    - restructuredtext-lint = restructuredtext_lint.cli:main
    - rst-lint = restructuredtext_lint.cli:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - docutils ==0.11

  run:
    - python
    - docutils ==0.11

test:
  # Python imports
  imports:
    - restructuredtext_lint
    - restructuredtext_lint.test

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - restructuredtext-lint --help
    - rst-lint --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/twolfson/restructuredtext-lint
  license: UNLICENSE
  summary: 'reStructuredText linter'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
