package:
  name: r-boot
  version: 1.3.13

source:
  fn: boot_1.3-13.tar.gz
  url: http://cran.r-project.org/src/contrib/boot_1.3-13.tar.gz

build:
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: MASS, survival
requirements:
  build:
    - r >=3.0.0
  run:
    - r >=3.0.0

test:
  commands:
    - R -e "library('boot')"

about:
  license: Unlimited
