package:
  name: fastcache
  version: !!str 0.1

source:
  fn: fastcache-0.1.tar.gz
  url: https://pypi.python.org/packages/source/f/fastcache/fastcache-0.1.tar.gz
  md5: 10f9526928639ae3de989e9fa0cc1b1f
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - fastcache = fastcache:main
    #
    # Would create an entry point called fastcache that calls fastcache.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - fastcache
    - fastcache.tests

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/pbrady/fastcache
  license:  MIT License
  summary: 'C implementation of Python 3 functools.lru_cache'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
