package:
  name: line_profiler
  version: !!str 1.0b3

source:
  hg_url: https://bitbucket.org/kmike/line_profiler

build:
  number: 1

requirements:
  build:
    - python
    - cython

  run:
    - python
    - cython

test:
  # Python imports
  imports:
    - line_profiler

  # This command actually gets installed properly without an entry point 
  # because it's a script
  commands:
    - kernprof.py --help

about:
  home: http://packages.python.org/line_profiler
  license: BSD License
