package:
  name: r-cluster
  version: 1.15.3

source:
  fn: cluster_1.15.3.tar.gz
  url: http://cran.r-project.org/src/contrib/cluster_1.15.3.tar.gz

build:
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: MASS
requirements:
  build:
    - r >=2.12.0
  run:
    - r >=2.12.0

test:
  commands:
    - R -e "library('cluster')"

about:
  license: GPL (>= 2)
