package:
  name: bipython
  version: !!str 0.1.2

source:
  fn: bipython-0.1.2.tar.gz
  url: https://pypi.python.org/packages/source/b/bipython/bipython-0.1.2.tar.gz
  md5: d2547028217a9a1a690ac2d7d36d9128
#  patches:
   # List any patch files here
   # - fix.patch

build:
  #preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - bipython = bipython:main
    #
    # Would create an entry point called bipython that calls bipython.main()

    - bipython = bipython:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pygments >=1.6
    - urwid >=1.1.1
    - bpython >=0.12
    - pyzmq >=2.1.11
    - ipython >=1.0

  run:
    - python
    - argparse # [py26]
    - pygments >=1.6
    - urwid >=1.1.1
    - bpython >=0.12
    - pyzmq >=2.1.11
    - ipython >=1.0

test:
  # Python imports
  imports:
    - bipython

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - bipython --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://bipython.org/
  license: BSD License
  summary: 'bipython: boldly indiscriminate python interpreter'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
