package:
  name: r-lattice
  version: 0.20.29

source:
  fn: lattice_0.20-29.tar.gz
  url: http://cran.r-project.org/src/contrib/lattice_0.20-29.tar.gz

build:
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: KernSmooth, MASS
# Enhances: chron
requirements:
  build:
    - r >=2.15.1
    - r-kernsmooth
    - r-mass
  run:
    - r >=2.15.1
    - r-kernsmooth
    - r-mass

test:
  commands:
    - R -e "library('lattice')"

about:
  license: GPL (>= 2)
