package:
  name: invoke
  version: "0.11.1"

source:
  fn: invoke-0.11.1.tar.gz
  url: https://pypi.python.org/packages/source/i/invoke/invoke-0.11.1.tar.gz
  md5: 3d4ecbe26779ceef1046ecf702c9c4a8

build:
  entry_points:
    - invoke = invoke.cli:main
    - inv = invoke.cli:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - invoke

  commands:
    - invoke --help
    - inv --help


about:
  home: http://docs.pyinvoke.org
  license: BSD License
  summary: 'Pythonic task execution'
