package:
  name: stomp.py
  version: !!str 4.0.12

source:
  fn: stomp.py-4.0.12.tar.gz
  url: https://pypi.python.org/packages/source/s/stomp.py/stomp.py-4.0.12.tar.gz
  md5: 355fa0bf0e0bb0d3661cd7ab7c3fd556
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - stomp.py = stomp.py:main
    #
    # Would create an entry point called stomp.py that calls stomp.py.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - stomp
    - stomp.adapter

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/jasonrbriggs/stomp.py
  license:  Apache Software License
  summary: 'Python STOMP client, supporting versions 1.0 and 1.1 of the protocol'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
