package:
  name: pyglet
  version: 1.1.4

source:
  fn: pyglet-1.1.4.tar.gz
  url: https://pypi.python.org/packages/source/p/pyglet/pyglet-1.1.4.tar.gz
  md5: 528c839ee8ceb763f697e0127b092aa4
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyglet = pyglet:main
    #
    # Would create an entry point called pyglet that calls pyglet.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - pyglet.gl
    - pyglet.font
    - pyglet.window.carbon [osx]
    - pyglet.media.drivers.openal [osx]
    - pyglet.window
    - pyglet.window.win32 [win]
    - pyglet.media.drivers.alsa [linux]
    - pyglet.image.codecs
    - pyglet.media.drivers
    - pyglet.media.drivers.directsound [win]
    - pyglet.text.formats
    - pyglet.image
    - pyglet.app
    - pyglet.text
    - pyglet.graphics
    - pyglet.window.xlib [linux]
    - pyglet.media
    - pyglet

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.pyglet.org/
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
