package:
    name: apache-storm
    version: 0.9.2

source:
    fn: apache-storm-0.9.2-incubating.tar.gz
    url: http://apache.petsads.us/storm/apache-storm-0.9.2-incubating/apache-storm-0.9.2-incubating.tar.gz
    md5: 02f7b04a2ee11dc8b2c65862fe84df85

build:
    number: 0

requirements:
    run:
        - jdk
        - python

test:
    commands:
        - storm help

about:
    home: http://storm.apache.org/
    license: Apache License v2.0

