package:
    name: apache-storm
    version: 0.9.3

source:
    fn: apache-storm-0.9.3.tar.gz
    url: http://mirrors.gigenet.com/apache/storm/apache-storm-0.9.3/apache-storm-0.9.3.tar.gz
    md5: 43353ebf96a4dc13e8712d759eb202a1

build:
    number: 2

requirements:
    run:
        - jdk
        - python

test:
    commands:
        - storm help

about:
    home: http://storm.apache.org/
    license: Apache License v2.0

