package:
  name: r-nnet
  version: 7.3.8

source:
  fn: nnet_7.3-8.tar.gz
  url: http://cran.r-project.org/src/contrib/nnet_7.3-8.tar.gz

build:
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: MASS
requirements:
  build:
    - r >=2.14.0
  run:
    - r >=2.14.0

test:
  commands:
    - R -e "library('nnet')"

about:
  license: GPL-2 | GPL-3
