package:
  name: readline
  version: 6.2

source:
  fn: readline-6.2.tar.gz
  url: ftp://ftp.cwru.edu/pub/bash/readline-6.2.tar.gz
  md5: 67948acb2ca081f23359d0256e9a271c

build:
  number: 2

about:
  home: http://cnswww.cns.cwru.edu/php/chet/readline/rltop.html
  license: GPL 3
