package:
  name: ml_metrics
  version: 0.1.3

source:
  fn: ml_metrics-0.1.3.zip
  url: https://pypi.python.org/packages/source/m/ml_metrics/ml_metrics-0.1.3.zip
  md5: 442a74b5e9fbe838386010555025c948

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pandas

  run:
    - python
    - numpy
    - pandas

test:
  # Python imports
  imports:
    - ml_metrics

about:
  home: https://github.com/benhamner/Metrics/tree/master/Python
  license: BSD 2-clause
