package:
  name: r-matrix
  version: 1.1.4

source:
  fn: Matrix_1.1-4.tar.gz
  url: http://cran.r-project.org/src/contrib/Matrix_1.1-4.tar.gz

build:
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: expm, MASS
requirements:
  build:
    - r >=2.15.2
    - r-lattice
  run:
    - r >=2.15.2
    - r-lattice

test:
  commands:
    - R -e "library('Matrix')"

about:
  license: GPL (>= 2)
