package:
  name: r-codetools
  version: 0.2.9

source:
  fn: codetools_0.2-9.tar.gz
  url: http://cran.r-project.org/src/contrib/codetools_0.2-9.tar.gz

build:
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: none
requirements:
  build:
    - r >=2.1
  run:
    - r >=2.1

test:
  commands:
    - R -e "library('codetools')"

about:
  license: GPL
