package:
  name: r-mgcv
  version: 1.8.4

source:
  fn: mgcv_1.8-4.tar.gz
  url: http://cran.r-project.org/src/contrib/mgcv_1.8-4.tar.gz

build:
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: splines, parallel, survival, MASS
requirements:
  build:
    - r >=2.14.0
    - r-nlme >=3.1.64
    - r-matrix
  run:
    - r >=2.14.0
    - r-nlme >=3.1.64
    - r-matrix

test:
  commands:
    - R -e "library('mgcv')"

about:
  license: GPL (>= 2)
