package:
  name: thriftpy
  version: !!str 0.1.3

source:
  fn: thriftpy-0.1.3.tar.gz
  url: https://pypi.python.org/packages/source/t/thriftpy/thriftpy-0.1.3.tar.gz
  md5: 1027d865d6714adb75927d34d0c787a7
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - thriftpy = thriftpy:main
    #
    # Would create an entry point called thriftpy that calls thriftpy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - cython
    - python
    - setuptools
    - pyparsing >=2.0.2

  run:
    - cython
    - python
    - pyparsing >=2.0.2

test:
  # Python imports
  imports:
    - thriftpy
    - thriftpy.protocol

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://lxyu.github.io/thriftpy/
  license: MIT License
  summary: 'Pure python implemention of Apache Thrift.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
