package:
  name: psychopy
  version: 1.78.01

source:
  fn: PsychoPy-1.78.01.zip
  url: http://psychopy.googlecode.com/files/PsychoPy-1.78.01.zip
  md5: effb51feeb9c2602583740b52bcbca75
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - psychopy = psychopy:main
    #
    # Would create an entry point called psychopy that calls psychopy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - avbin
    - numpy
    - scipy
    - pyglet
    - wxpython
    - pillow
    - matplotlib
    - lxml
    - openpyxl
    - pyo
    - pywin32 [win]
    - winioport [win]
    - inpout32 [win32]
    - inpoutx64 [win64]
  run:
    - python
    - setuptools
    - avbin
    - numpy
    - scipy
    - pyglet
    - wxpython
    - pillow
    - matplotlib
    - lxml
    - openpyxl
    - pyo
    - pywin32 [win]
    - winioport [win]
    - inpout32 [win32]
    - inpoutx64 [win64]
    - pyparallel [linux]

test:
  # Python imports
  imports:
    - psychopy

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.psychopy.org/
  license: GNU General Public License v3 (GPLv3)

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
