package:
  name: emacs
  version: 24.4

source:
  fn: emacs-24.4.tar.xz
  url: http://ftp.gnu.org/gnu/emacs/emacs-24.4.tar.xz
  md5: ad487658ad7421ad8d7b5152192eb945

build:
  number: 2
  detect_binary_files_with_prefix: true

requirements:
  build:
    - libxml2
    - ncurses
    - dbus
  run:
    - libxml2
    - ncurses
    - dbus

test:
  commands:
    - emacs --help
    - emacs --kill

about:
  home: http://www.gnu.org/software/emacs/
  license: GPL
  summary: "GNU Emacs is an extensible, customizable text editor—and more."
