package:
  name: statsmodels
  version: "0.5.0"

source:
  git_url: https://github.com/statsmodels/statsmodels.git
  git_tag: v0.5.0

build:
  script: python setup.py install

requirements:
  build:
    - python
    - numpy
    - cython
    - distribute
    - scipy
    - pandas
    - patsy
  run:
    - python
    - numpy
    - cython

test:
  imports:
    - statsmodels

about:
  home: http://statsmodels.sourceforge.net/
  license : BSD License
