package:
  name: jdk
  version: "1.8.0.31.13"

requirements:
  build:
    - curl

test:
  commands:
    - java -version

about:
  home: http://www.oracle.com/technetwork/java/javase/
  license: Oracle Binary Code License Agreement
